### PR TITLE
Update build system / cleanup

### PR DESCRIPTION
**Pull request by wdlkmpx**
The repo has really ancient autotools stuff, so it's time to get rid of it.

New configure.ac
New autogen.sh
New .gitignore

This stuff should work fine in distros released since 2006-2007, I guess..

How to compile from git:
- ./autogen.sh
- ./configure --prefix=/usr
- make install

Releases could have a tarball with the stuff generated by ./autogen.sh..

How to do dev work:
- compile and install
- test, edit files
- commit changes
- run `git clean -dfx` to clean directory tree

### CODE REVIEW

**Comment by emorozov** [comment]
Thank you! This is very cool.

Though I've started a port to GTK4 just yesterday and I'm going to use meson for it. It just seems much easier and faster than autoconf/autotools.

But I'll probably merge your work because I'm not sure how much time GTK4 port will consume, there're too many changes from GTK2 to GTK4.

**Comment by wdlkmpx** [comment]
I don't recommend porting directly to gtk4. Gtk3 is finalized and stable, and the gtk4 nightmare has just begun.

The toolkit has changed too much. It looks the best in gtk2, it's quite ugly in gtk3 and probably even uglier in gtk4.

Overall you'll need to be cairo guru, but cairo works the same in gtk2/3 and 4 probably.

**Comment by emorozov** [comment]
But GTK4 has been officially released in December. I took it as a hint to continue development of GtkBalls which I neglected for about 20 years.

Unfortunately, I had almost zero experience working with C and/or Gtk (except some short stints with PyGTK) during all those 20 years, so it's a bit painful experience. I also understand that overall architecture of GtkBalls is not very elegant and fool proof. It was my first (and last) big program in C.

I just don't want to waste time doing the port two times. Yes, it seems that Gtk3 port would be much easier, although I'd need to rewrite all drawing code in Cairo anyway, even if using Gtk3.

**Comment by wdlkmpx** [comment]
Well, cairo is "outside" gtk,  and the changes with cairo drawing basically work the same in gtk2/gtk3. The learning cairo takes time.

The windows/dialogs .. are mostly compatible between gtk2/3, but gtk4 is another, different beast.

**Comment by wdlkmpx** [comment]
Gtk3 received a lot of hate because it looked more primitive with less widgets and was WAY heavier than gtk2.. performance issues not really accepted in C, it has improved since then. But many still miss the gtk2 level of customization.

If you haven't used C and GTK in 20 years, you'll probably struggle too much.

This is low level stuff compared to other languages, Ive been editing gtk projects for 2 years and my knowledge is very limited, I learn as I go, I forget and learn again.

As this PR deletes a lot of files, you can just merge this and then delete the 2 added files and the remaining makefile.in/am files.

**Comment by wdlkmpx** [comment]
I know what widgets are compatible with gtk2/gtk3/gtk4.

The big change is cairo, and cairo is consistent between gtk2/3/4.

I can try to update stuff to gtk3 while still supporting gtk2, and all this with autotools as it's ready, changes are easy from now on.

All GdkPixmap stuff must be converted to GdkPixbuf and cairo, that might be too hard for me, so in even gtk3 support might be far away.

At this point i'm not interested in gtk4 as it will take 10 years to reach a stable status.

**Review by emorozov — APPROVED** [review]

**Pull request merged**
